export const BLOCKSCOUT_SEPOLIA_LISK_SCAN =
  process.env.NEXT_PUBLIC_BLOCKSCOUT_SEPOLIA_LISK_SCAN;

export const LISK_SEPOLIA_TX_HASH_ROUTE = `${BLOCKSCOUT_SEPOLIA_LISK_SCAN}/api/v2/transactions/`;
export const LISK_SEPOLIA_TX_HASH_URL = `${BLOCKSCOUT_SEPOLIA_LISK_SCAN}/tx/`;
